title: Horace Cheng
theme: jekyll-theme-minimal
url: "https://hcheng25.github.io" # your site URL
baseurl: "" # leave empty for user site, '/repo' for project site
author: Horace Cheng
email: horace.cheng@ucsf.edu
logo: "images/hc_headshot.jpg"

